services:
  hetzner-auction-hunter:
    container_name: hetzner-auction-hunter
    image: hetzner-auction-hunter:latest
    volumes:
      - ./tmp/hah:/tmp/
    environment:
    command: --price 38 --disk-size 3000 --ram 24
    restart: unless-stopped
